# Generated by Django 5.1.4 on 2024-12-25 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('actives', models.ManyToManyField(related_name='actives', to=settings.AUTH_USER_MODEL, verbose_name='активные пользователи')),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='пользователи')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, 'активный'), (2, 'удален')], default=1, verbose_name='состояние')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст сообщения')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='вложенный файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='дата удаления')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
                ('to_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chats.chat', verbose_name='получатель: чат')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user_messages', to=settings.AUTH_USER_MODEL, verbose_name='получатель: пользователь')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('changed_at',),
            },
        ),
        migrations.CreateModel(
            name='OnlineUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активность')),
                ('last_date', models.DateTimeField(auto_now=True, verbose_name='дата последнего входа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'онлайн пользователи',
                'verbose_name_plural': 'онлайн пользователи',
                'ordering': ('-last_date',),
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateTimeField(auto_now_add=True, verbose_name='дата прочтения сообщения')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.message', verbose_name='сообщение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'читатель',
                'verbose_name_plural': 'читатели',
                'ordering': ('-read_date',),
            },
        ),
        migrations.AddField(
            model_name='message',
            name='readers',
            field=models.ManyToManyField(related_name='read_messages', through='chats.Reader', to=settings.AUTH_USER_MODEL),
        ),
    ]
